
services:
  apache:
    container_name: apa
    build:
      target: apache
    tty: true
    stdin_open: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./volumes/:/app
  db:
    container_name: db
    build:
      target: db
    tty: true
    stdin_open: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./volumes/llibres:/app
  myadmin:
    container_name: admin
    build:
      target: myadmin
    tty: true
    stdin_open: true
    ports:
      -  "8080:8080"
    environment:
      PMA_HOST: db
